{{ if .Values.descheduler.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: crane-descheduler-policy
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
         enabled: false
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: false
      "ReduceHighLoadNode":
         enabled: true
         {{- if .Values.loadThreshold }}
         params:
           nodeload:
             numberOfNodes: {{ .Values.loadThreshold.numberOfNodes }} 
             maxCoresPercent: {{ .Values.loadThreshold.maxCoresPercent }} 
             enableDynamicThreshold: 
               enable: {{ .Values.loadThreshold.enableDynamicThreshold.enabled }} 
               enableDefault: {{ .Values.loadThreshold.enableDynamicThreshold.enabledDefault }} 
             {{- if eq (.Values.loadThreshold.enableDynamicThreshold.enabledDefault | toString) "True" }} 
             thresholds:
               "cpu": {{ .Values.loadThreshold.cpuAvgUsage5M }}
               "memory": {{ .Values.loadThreshold.memAvgUsage5M }}
             targetThresholds:
               "cpu": {{ .Values.loadThreshold.cpuTargetUsage }}
               "memory": {{ .Values.loadThreshold.memTargetUsage }}
             {{- end }}
         {{- end }}
      "RestartPodForEvent":
         enabled: false
         params:
           configValues:
             "containercheck": "100"
             "policy": "restartlocal"
{{- end }}