apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crane-scheduler
  name: crane-scheduler
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crane-scheduler
  template:
    metadata:
      labels:
        app: crane-scheduler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: crane-scheduler
      containers:
        - name: scheduler
          env:
            - name: TZ
              value: Asia/Shanghai
          command:
            - /scheduler
            - --policy-config-path=/data/policy.yaml
            - --server-enable-profiling=true
            - --server-enable-metrics=true
            - --v=6
          image: {{ .Values.global.image.host }}/tkeimages/crane-scheduler:v1.0.2
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 8088
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 8088
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /data
              name: crane-scheduler-policy
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: crane-scheduler-policy
          name: crane-scheduler-policy
