{{ if .Values.controller.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: crane-scheduler
      restartPolicy: Never
      containers:
      - name: helmhook
        image: {{ .Values.global.image.host }}/{{ .Values.global.image.repo }}/crane-scheduler-helmhook:{{ .Values.global.image.tag }}
        imagePullPolicy: Always
        command:
          - /helmhook
          - --deployment-controller-to-stop-namespace=kube-system
          - --deployment-controller-to-stop=crane-scheduler-controller
          - --clear-node-annotation-prefix=target.balance.scheduling.crane.io
          - --clear-node-annotation-prefix=load.balance.scheduling.crane.io
          - --clear-node-annotation-prefix=evict.balance.scheduling.crane.io
          - --clear-node-annotation-prefix=expansion.scheduling.crane.io
{{- end }}