{{ if .Values.scheduler.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crane-scheduler
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - list
  - watch
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
    - "scheduling.crane.io"
  resources:
    - clusternoderesourcepolicies
    - noderesourcepolicies
    - craneschedulerconfigurations
  verbs:
    - get
    - list
    - watch
    - update
    - create
    - patch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crane-scheduler
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crane-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crane-scheduler
subjects:
- kind: ServiceAccount
  name: crane-scheduler
  namespace: kube-system
{{- end }}
---
{{ if .Values.descheduler.enabled -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crane-descheduler
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list","patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: ["*"]
    resources: ["replicasets"]
    verbs: ["get"]
  - apiGroups: ["*"]
    resources: ["deployments"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
  - apiGroups: ["platform.stke"]
    resources: ["statefulsetpluses"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["jobs"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crane-descheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crane-descheduler
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crane-descheduler
subjects:
  - name: crane-descheduler
    kind: ServiceAccount
    namespace: kube-system
{{- end }}