{{ if .Values.controller.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: crane-scheduler-controller
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app: crane-scheduler-controller
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
      name: webhook
    - name: metrics-http
      port: 8088
      protocol: TCP
      targetPort: 8088
{{- end }}