FROM alpine:3.11.0
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add -U tzdata
RUN apk add curl
#RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

COPY _output/bin/${NAME} /${NAME}
