apiVersion: v1
kind: ConfigMap
metadata:
  name: crane-scheduler-policy
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: scheduler.policy.crane.io/v1alpha1
    kind: DynamicSchedulerPolicy
    spec:
      syncPolicy:
        - name: cpu_usage_avg_5m
          period: 5m
        - name: cpu_usage_max_avg_1h
          period: 30m
        - name: cpu_usage_max_avg_1d
          period: 3h
        - name: mem_usage_avg_5m
          period: 5m
        - name: mem_usage_max_avg_1h
          period: 30m
        - name: mem_usage_max_avg_1d
          period: 3h

      predicate:
        - name: cpu_usage_avg_5m
        - name: cpu_usage_max_avg_1h
        - name: mem_usage_avg_5m
        - name: mem_usage_max_avg_1h

      priority:
        - name: cpu_usage_avg_5m
          weight: 0.2
        - name: cpu_usage_max_avg_1h
          weight: 0.3
        - name: cpu_usage_max_avg_1d
          weight: 0.5
        - name: mem_usage_avg_5m
          weight: 0.2
        - name: mem_usage_max_avg_1h
          weight: 0.3
        - name: mem_usage_max_avg_1d
          weight: 0.5

      hotValue:
        - timeRange: 5m
          count: 5
        - timeRange: 1m
          count: 2