apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crane-scheduler
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - list
  - watch
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
    - "scheduling.crane.io"
  resources:
    - clusternoderesourcepolicies
    - noderesourcepolicies
    - craneschedulerconfigurations
  verbs:
    - get
    - list
    - watch
    - update
    - create
    - patch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crane-scheduler
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crane-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crane-scheduler
subjects:
- kind: ServiceAccount
  name: crane-scheduler
  namespace: kube-system